int func () {
    outputchar('&');
    return;
}

int main () {
    int jack[20];
    int a;
    int b;
    int c;
    int d;
    int e;
    int f;
    int g;
    int h;
    int i;
    int j;
    int k;
    int l;


    a = 1;
    b = 2;
    c = 3;
    d = 4;
    e = 5;
    f = 6; 
    g = 7;
    h = 8;
    i = 9;
    j = 10;
    k = 11;
    l = 12;

    output(a);
    output(b);
    output(c);
    output(d);
    output(e);
    output(f);
    output(g);
    output(h);
    output(i);
    output(j);
    output(k);
    output(l);

    func();
}